-- create sequence
CREATE SEQUENCE IF NOT EXISTS SEQ_ROCHE_PRODUCT_ID START WITH 1 INCREMENT BY 50;
-- create table
CREATE TABLE IF NOT EXISTS PRODUCT (
id INTEGER AUTO_INCREMENT  PRIMARY KEY,
name VARCHAR(50) NOT NULL,
price DOUBLE NOT NULL,
date DATE NOT NULL,
is_active BOOLEAN NOT NULL
);


